---
name: Update

'on':
  schedule:
    - cron: '0 7 1 * *'  # At 07:00 on day-of-month 1
  workflow_dispatch:

jobs:
  lock-updater:
    name: Flake Lock Updater
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/update-flake-lock@v21
        with:
          pr-title: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated
